LOG_LEVEL=INFO
AWS_SECRET_REGION=ap-south-1
DATABRICKS_ANALYTICSHOST=https://swiggy-analytics-mumbai.cloud.databricks.com/
DATABRICKS_ANALYTICS_MUMBAI_TOKEN_SECRET_NAME=/swiggy.cloud/production/ap-south-1/dbr-notifier/DATABRICKS_ANALYTICS_MUMBAI_TOKEN
OPSGENIE_API_KEY_SECRET_NAME=/swiggy.cloud/production/ap-south-1/dbr-notifier/OPSGENIE_API_KEY